steps:
- name: 'gcr.io/cloud-builders/gradle:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export buildVersion="0.0.0"
    export helixRepoUser=${_REPO_PASSWORD}
    export helixRepoPassword=${_REPO_USER}
    gradle clean build -PhelixRepoUser=${_REPO_USER} -PhelixRepoPassword={$_REPO_PASSWORD} -PbuildVersion=$$buildVersion
   